### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by xyproto** [prathyvsh/pl-catalog#5]
Here are a few more:

http://rosettacode.org/wiki/Category:Programming_Languages

**Comment by prathyvsh** [comment]
@xyproto Hi, thanks for the list.My original intend was to capture the up and coming interesting/promising programming languages made by passionate indie people and which are lesser known. I will look through that list and add ones which suit this intend, thanks!

**Comment by xyproto** [comment]
I see. If I had known (if ie. this information was in the README), I would not have created the pull request. Thanks for assembling what appears to be a very nice list, though. :smile:

**Comment by prathyvsh** [comment]
@xyproto No, your Battlestar project definitely belongs in this list.

I am waiting to clear up some of the stuff I am focusing on the moment before merging your PR.

Battlestar looks pretty interesting! Great going on that one.
